// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ArventureApi.Models
{
    public partial class Carte
    {
        public int Id { get; set; }
        public string Img { get; set; }
        public string Title { get; set; }
        public string Alt { get; set; }
    }
}