// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ArventureApi.Models
{
    public partial class Histoire
    {
        public int Id { get; set; }
        public string Content { get; set; }
    }
}